# vim: set ft=yaml:
# https://www.docker.elastic.co
---
version: '2.3'

services:

  # dev:
  #   image: ubuntu
  #   volumes:
  #     # '~/.docker_bash_history' file should exist before mounting
  #     - $HOME/.docker_bash_history:/root/.bash_history

  dev:
    image: ubuntu

    volumes:
      - $HOME/.docker_bash_history:/root/.bash_history

    #  - ${DEVILBOX_PATH}/bash_history:/home/devilbox/.bash_history  

  # -----------------------------------------------------------------------------------------------
  # ELK Stack
  # -----------------------------------------------------------------------------------------------
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_SERVER:-6.6.1}
    hostname: elastic
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_ELK_ELASTIC:-9200}:9200"
    networks:
      app_net:
        ipv4_address: 172.16.238.240
    environment:
      - TZ=${TIMEZONE:-UTC}
      - discovery.type=single-node
    volumes:
      - devilbox-elastic:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${ELK_SERVER:-6.6.1}
    hostname: kibana
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_ELK_KIBANA:-5601}:5601"
    networks:
      app_net:
        ipv4_address: 172.16.238.242
    environment:
      - TZ=${TIMEZONE:-UTC}
      - ELASTICSEARCH_URL=http://elastic:9200
    depends_on:
      - elastic
      
  rabbit:
    image: rabbitmq:${RABBIT_SERVER:-management}
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_VHOST=${RABBIT_DEFAULT_VHOST:-my_vhost}
      - RABBITMQ_DEFAULT_USER=${RABBIT_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_DEFAULT_PASS:-guest}
    ports:
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_RABBIT:-5672}:5672"
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_RABBIT_MGMT:-15672}:15672"
    networks:
      app_net:
        ipv4_address: 172.16.238.210
    volumes:
      - devilbox-rabbit:/var/lib/rabbitmq
    depends_on:
      - bind
      - php
      - httpd

volumes:
  devilbox-elastic:

  devilbox-rabbit:
